[remote.github]
owner = "overflow65537"
repo = "MAA_SnowBreak"
[changelog]
# 尾部
footer = """

如果不清楚要下哪个,请点击[此处进行下载](https://github.com/overflow65537/MAA_Punish/releases/download/{{version}}/MPA-win-x86_64-{{version}}.zip)
[已有 Mirror酱 CDK？点击前往高速下载](https://mirrorchyan.com/zh/projects?rid=MAA_SnowBreak)
<!--本软件完全免费，若您有付费购买请立即退款并举报！-->
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages

# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "新增 | Feat" },
    { message = "^fix", group = "修复 | Fix" },
    { message = "^docs", group = "文档 | Docs" },
    { message = "^perf", group = "优化 | Perf" },
    { message = "^refactor\\(clippy\\)", skip = true },
    { message = "^refactor", group = "重构 | Refactor" },
    { message = "^style", group = "样式 | Style" },
    { message = "^test", group = "测试 | Test" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
    { message = "^chore", group = "杂项 | Chore" },
    { message = "^other", group = "其它 | Other" },
    { message = "^ci", group = "集成 | CI" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# regex for matching git tags
tag_pattern = "v[0-9].*"
# regex for skipping tags
skip_tags = "beta|alpha"
# regex for ignoring tags
ignore_tags = "rc"
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "newest"